# Heavily based on the .pre-commit-config.yaml for pandas, permitted under its BSD-3-Clause license,
# which is shared by Joinplex:
# https://github.com/pandas-dev/pandas

minimum_pre_commit_version: 2.15.0 # Sync with environment.yml
# reserve "manual" for mypy and pyright
default_stages:
  [
    commit,
    merge-commit,
    push,
    prepare-commit-msg,
    commit-msg,
    post-checkout,
    post-commit,
    post-merge,
    post-rewrite,
  ]
ci:
  autofix_prs: false
repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        files: ^joinplex/

  - repo: https://github.com/python/black
    rev: 22.3.0 # Sync with environment.yml
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        stages: [manual]
        additional_dependencies: &pyright_dependencies
          - pyright@1.1.264

      - id: pyright_reportGeneralTypeIssues
        name: pyright reportGeneralTypeIssues
        entry: pyright --skipunannotated -p pyright_reportGeneralTypeIssues.json
        language: node
        pass_filenames: false
        types: [python]
        stages: [manual]
        additional_dependencies: *pyright_dependencies

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        types: [python]
        stages: [manual]
