# Based on the environment.yml for pandas, permitted under its BSD-3-Clause license,
# which is shared by Joinplex:
# https://github.com/pandas-dev/pandas
name: joinplex-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # test dependencies
  - pytest>=6.0m
  - pytest-cov
  - pytest-xdist>=1.31

  # required dependencies
  - pandas

  # code checks
  - black=22.3.0
  - pylint>=2.7.0
  - isort>=5.2.1
  - mypy=0.981
  - pre-commit>=2.15.0

  # documentation
  - sphinx
