[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools_scm>=7",
]

[tool.black]
target-version = ['py38', 'py39', 'py310']
exclude = '''
(
  \.git
  | setup.py
)
'''

[tool.pylint.messages_control]
max-line-length = 88
